# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d254ed86448b03bbbaff0669f49025eb14db28b0fbe30493432ec77f7ab7695f919f7e7abc6a263e46a68588673ec281bf98bb2208d1c0d6d8d4b6c669d4f916

test:
  secret_key_base: 33d6e2aeaf8151d5b45b163e13d8d8c0c1e2b4275896f0ec8ae0c7ef46234eb1d3db11a3147c03cdb961d4fb49ba0c13b4bacb7f5d7e55e3b3eeb461ad76d8a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
